# input_quantizer:
#     bit_width: 8
#     signed: True
#     narrow_range: False
#     quant_type: QuantType.INT
#     min_val: -1.0
#     max_val: 0.9921875 # 1-2**-7
#     scaling_per_output_channel: False
#     float_to_int_impl_type: FloatToIntImplType.ROUND
#     scaling_impl_type: ScalingImplType.CONST
#     restrict_scaling_type: RestrictValueType.POWER_OF_TWO
#     bit_width_impl_type: BitWidthImplType.CONST

weight_quantizer:
    bit_width: 2
    signed: True
    narrow_range: False
    quant_type: QuantType.INT
    scaling_const: 1.0
    scaling_per_output_channel: False
    float_to_int_impl_type: FloatToIntImplType.ROUND
    scaling_impl_type: ScalingImplType.STATS
    scaling_stats_op: StatsOp.AVE
    restrict_scaling_type: RestrictValueType.POWER_OF_TWO
    bit_width_impl_type: BitWidthImplType.CONST

activation_quantizer:
    bit_width: 8
    # signed: True
    # narrow_range: False
    # quant_type: QuantType.INT
    # min_val: -1
    # max_val: 0.875 # 1-2**-3
    # scaling_const: 1.0
    # scaling_per_output_channel: False
    # scaling_stats_permute_dims: 1,0,2
    # per_channel_broadcastable_shape: 1,64,1
    # float_to_int_impl_type: FloatToIntImplType.ROUND
    # scaling_impl_type: ScalingImplType.CONST
    # scaling_stats_op: StatsOp.AVE
    # restrict_scaling_type: RestrictValueType.POWER_OF_TWO
    # bit_width_impl_type: BitWidthImplType.CONST

