_target_: src.models.trainer_module.TrainerModule
lr: 0.0001
weight_decay: 0
milestones: 50,75
gamma: 0.1

net:
  _target_: src.models.components.vit_small.ViT
  image_size: 32
  patch_size: 4
  num_classes: 10
  dim: 512
  depth: 4
  heads: 6
  mlp_dim: 256
  SA_SIZE: 256
  dropout: 0.1
  emb_dropout: 0.1