_target_: src.models.trainer_module.TrainerModule
lr: 0.0001
weight_decay: 0
milestones: 50,75
gamma: 0.1

net:
  _target_: src.models.components.vit_naive.SimpleViT
  input_size: 3
  emb_dim: 64
  output_size: 10
  quantization: False
  dropout: 0
