_target_: src.datamodules.cifar10_datamodule.CIFAR10DataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [50_000, 10_000, 0]
num_workers: 4
pin_memory: True
